# Generated by Django 4.0.1 on 2023-01-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_picture_productpicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'Product Attributes'},
        ),
        migrations.AddField(
            model_name='banner',
            name='desc',
            field=models.CharField(default='rifjrfjr', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='defrfrfee', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(default='efrfrfree', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='DEW232', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='size_code',
            field=models.CharField(default='desw', max_length=10),
            preserve_default=False,
        ),
    ]
