# Generated by Django 4.0.1 on 2023-01-11 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productattribute_options_banner_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='discount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
