# Generated by Django 4.0.1 on 2023-01-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productattribute_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='discount',
            field=models.FloatField(),
        ),
    ]
